### ISSUE TITLE
[Quotes] AttributeError: 'NoneType' object has no attribute 'url'

### ISSUE THREAD

**Issue by zawnk** [Flame442/FlameBountyCogs#3]
If you call `<p>quote` without any params, I'm running into the above mentioned error and the stack points to this place:

https://github.com/Flame442/FlameBountyCogs/blob/26432c19efde61bebf8be39b7099b657eb53667e/quotes/quotes.py#L116C1-L116C82

If you call it with a user that's on the server, it works just fine (e.g. `<p>quote @User`). As a temporary workaround, I just removed the `icon_url` param. Not sure why it can't fetch the `author.avatar.url`.

Edit: `icon_url=author.avatar.url if author.avatar else author.default_avatar.url` seems to do the trick

**Comment by Flame442** [comment]
Thank you for reporting this issue!
